Fix how go is installed. Fix how we wait for github

diff --git a/new_machine_setup/setup_new_machine b/new_machine_setup/setup_new_machine
--- a/new_machine_setup/setup_new_machine
+++ b/new_machine_setup/setup_new_machine
@@ -27,15 +27,6 @@ setup_ssh() {
 	cat "${HOME}/.ssh/id_ed25519.pub"
 	read -n 1 -s -r </dev/tty # /dev/tty prevents confusion of stdin when the script is curled into bash
 	echo
-	while true; do
-		if ssh -o BatchMode=yes -o StrictHostKeyChecking=no -T git@github.com 2>&1 | grep -q "successfully authenticated"; then
-			echo "SSH key is now working!"
-			break
-		else
-			echo "Waiting for SSH key to propagate..."
-			sleep 5
-		fi
-	done
 }
 setup_ssh
 
@@ -142,7 +133,6 @@ install fish
 install fontconfig
 install fzf
 install git
-install go
 install grep
 install moreutils
 install ncdu
@@ -162,7 +152,10 @@ rm -f "${HOME}/.zshrc"
 rm -f "${HOME}/.config"
 mkdir -p "${HOME}/dev" || exit 1
 rm -rf "${HOME}/dev/dotfiles"
-git clone git@github.com:BrendanNolan/dotfiles.git "${HOME}/dev/dotfiles"
+while ! git clone git@github.com:BrendanNolan/dotfiles.git "${HOME}/dev/dotfiles"; do
+	echo "Could not clone from github, hopefully because github is processing the new ssh keys"
+	sleep 5
+done
 rm -rf "${HOME}/dev/scripts"
 git clone git@github.com:BrendanNolan/scripts.git "${HOME}/dev/scripts"
 source "${HOME}/.bash_profile"
@@ -185,6 +178,7 @@ install_for_macos() {
 	install 'dlvhdr/formulae/diffnav'
 	install 'felixkratz/formulae/borders'
 	install gh
+	install go
 	install gnu-sed
 	install 'homebrew-zathura/zathura/zathura'
 	install 'homebrew-zathura/zathura/zathura-pdf-poppler'
@@ -208,6 +202,7 @@ install_for_fedora() {
 	sudo dnf install -y gh --repo gh-cli
 
 	install fira-code-fonts
+	install golang
 	install nodejs
 	install procps-ng
 	install shfmt
@@ -218,6 +213,7 @@ install_for_debianlike() {
 	install build-essential
 	install fonts-firacode
 	install gh
+	install golang-go
 	install nodejs
 	install npm
 	install procps
